cryptobattles
ed3ath/cb-api-nfts pull request #3
Opened 2022-06-15 15:57 UTC by Ksuyaresko

2022-06-16 12:42 UTC, byyyyyyyyy commented on config/cryptobattles.json
> +  "preprocessor": "cryptobattles.js", // the file name of the preprocessor script (see the preprocessor example below)
comments aren't allowed on a json file. kindly remove them.

2022-06-16 12:42 UTC, byyyyyyyyy commented on preprocessor/cryptobattles.js
> +    name: nftdata.name,
any additional properties that you want to show? image, etc.

2022-06-16 12:43 UTC, byyyyyyyyy reviewed
additional change requests

2022-06-16 13:42 UTC, Ksuyaresko commented on preprocessor/cryptobattles.js
> +    name: nftdata.name,
There is no metadata in our nft

2022-06-16 13:44 UTC, Ksuyaresko commented on config/cryptobattles.json
> +  "preprocessor": "cryptobattles.js", // the file name of the preprocessor script (see the preprocessor example below)
done

2022-07-14 13:59 UTC, byyyyyyyyy commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
address is not existing on testnet

2022-07-14 13:59 UTC, byyyyyyyyy commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
need exactly to return the json data

2022-07-14 19:14 UTC, Ksuyaresko commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
this is test nft on binance smart chain, not testnet

2022-07-14 19:16 UTC, Ksuyaresko commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
sorry, I don't understand that exactly you mean. It is link to .json file. What t should be?

2022-07-15 13:29 UTC, byyyyyyyyy commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
sample abi for our Character nft. you can try visiting. https://app.cryptoblades.io/abi/Characters.json

2022-07-15 13:34 UTC, byyyyyyyyy commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
hmm i see. the test object is expecting testnet contract addresses.

2022-07-15 13:53 UTC, ed3ath requested changes

2022-07-15 13:53 UTC, ed3ath commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
source must be in raw if it's hosted in github

2022-07-15 13:53 UTC, ed3ath commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
please provide a valid token address.

2022-07-15 13:53 UTC, ed3ath commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
please provide a nft address for testnet, not mainnet.

2022-07-15 13:53 UTC, ed3ath commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
you provided a link to github page. the link must return a json response.

2022-07-15 14:16 UTC, Ksuyaresko commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
binance testnet ? or rinkeby is ok?

2022-07-15 14:31 UTC, Ksuyaresko commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
done

2022-07-15 14:59 UTC, Ksuyaresko commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
done

2022-07-15 16:25 UTC, Ksuyaresko commented on config/cryptobattles.json
> +    "source": "https://github.com/Ksuyaresko/betting-abi/blob/master/abi-nft.json"
done

2022-07-18 11:28 UTC, byyyyyyyyy commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
we don't have support for rinkeby. we do have for bsc though

2022-07-18 16:54 UTC, Ksuyaresko commented on config/cryptobattles.json
> +        "BSC": "0x1034E332aEe10a0d0e0017c607B1276aCA541022"
deployed to BSC testnet

2022-07-18 22:13 UTC, merged

2022-07-18 22:17 UTC, ed3ath commented
@Ksuyaresko can you mint at least 5 nfts on bsc tesnet and sent them to this address? 0x2548696795a3bCd6A8fAe7602fc26DD95A612574

2022-07-20 07:26 UTC, Ksuyaresko commented
> @Ksuyaresko can you mint at least 5 nfts on bsc tesnet and sent them to this address? 0x2548696795a3bCd6A8fAe7602fc26DD95A612574

done. tokenId: 1, 2, 3, 4, 5, 6